server:
  port: 9002
spring:
  application:
    name: consumer-feign-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: info
